[arm/stm32f4]
# Selects the compiler used to build the BSP (allowed values are "gcc" and
# "clang").  Please note that the values of some options depend on the compiler
# selection and changing the compiler may lead to unpredictable behaviour if
# these options are not adjusted as well.  Use the --rtems-compiler command line
# option to get the default values for a particular compiler via
# ./waf bspdefaults.
COMPILER = clang
# There are dependencies between the RTEMS sources and external
# interfaces provided by Newlib and GCC.  For example, POSIX API
# interfaces may change due to POSIX standard updates.  The GCC build
# key is used to provide an indication that the present tools meet the
# requirements of the RTEMS sources. The GCC build key policy defines
# how the build key of the present compiler is checked against the
# required build key.  While the policy is "ERROR", if the GCC build
# key has not the expected value, then the build configuration process
# produces a fatal error.  While the policy is "WARNING", if the GCC
# build key has not the expected value, then the build configuration
# process produces a warning message.  While the policy is "IGNORE",
# the GCC build key is not checked at all.  The default policy is
# "WARNING".
GCC_BUILD_KEY_POLICY = WARNING
# Defines the program prefix of tools (compiler, assembler, linker)
# used to build RTEMS. This option may be used to build RTEMS with a
# vendor tool suite. Please note, support issues related to using this
# option with vendor tool suites should be directed to the vendor of
# the tools.
PROGRAM_PREFIX = ${ARCH}-rtems${__RTEMS_MAJOR__}-
# Flags passed to the library archiver
ARFLAGS = crD
# Specifies the C Language version and additional APIs available to
# the program. gnuNN allows GCC extensions and POSIX APIs. Switching
# to stdNN requires the addition of -D_POSIX_C_SOURCE=202405L to
# compile for POSIX Issue 8 that RTEMS is aligned to.
CC_STD_VERSION_FLAGS = -std=gnu23 -D_BSD_SOURCE
# Warning flags passed to the C and C++ compiler
WARNING_FLAGS = -Wall -Wextra -Werror
# Warning flags passed to the C compiler
CC_WARNING_FLAGS = -Wno-error -Wmissing-prototypes -Wimplicit-function-declaration -Wstrict-prototypes -Wnested-externs -Wno-parentheses-equality -Wno-asm-operand-widths -Wno-gnu-variable-sized-type-not-at-end -Wno-sign-compare -Wno-default-const-init-var-unsafe -Wno-unused-function
# Warning flags passed to the C++ compiler
CXX_WARNING_FLAGS = -Wno-error -Wno-unknown-warning-option -Wno-unused-private-field -Wno-extern-c-compat
# Enable the Ada support
__RTEMS_ADA__ = False
# Defines the build label returned by rtems_get_build_label().
RTEMS_BUILD_LABEL = DEFAULT
# Default size in CAN frames of FIFO queues.
RTEMS_CAN_FIFO_SIZE = 64
# Number of available priorities for CAN priority queues.
RTEMS_CAN_QUEUE_PRIO_NR = 3
# Enable the RTEMS internal debug support
RTEMS_DEBUG = False
# Enable the Driver Manager startup
RTEMS_DRVMGR_STARTUP = False
# Enable the Newlib C library support
RTEMS_NEWLIB = True
# Enable the para-virtualization support
RTEMS_PARAVIRT = False
# Enable support for POSIX signals, sporadic server and lio_listio()
RTEMS_POSIX_API = False
# Enable the SMP lock profiling support
RTEMS_PROFILING = False
# Enable the code and branch coverage support.
RTEMS_GCOV_COVERAGE = False
# Compiler flags recommended for components which should generate
# coverage information.
COVERAGE_COMPILER_FLAGS = 
# Linker flags recommended for executables which contain modules which
# generate coverage information.
COVERAGE_LINKER_FLAGS = 
# Enable support for JFFS2 Erase Block Summary (EBS)
CONFIG_JFFS2_SUMMARY = False
# Build the test programs
BUILD_TESTS = True
# Build the Ada test programs (may be also enabled by BUILD_TESTS)
BUILD_ADATESTS = True
# Build the benchmark programs (may be also enabled by BUILD_TESTS)
BUILD_BENCHMARKS = True
# Build the file system test programs (may be also enabled by
# BUILD_TESTS)
BUILD_FSTESTS  = True
# Build the library test programs (may be also enabled by BUILD_TESTS)
BUILD_LIBTESTS = True
# Build the MPCI test programs (may be also enabled by BUILD_TESTS)
BUILD_MPTESTS = True
# Build the POSIX test programs (may be also enabled by BUILD_TESTS)
BUILD_PSXTESTS = True
# Build the POSIX timing test programs (may be also enabled by
# BUILD_TESTS)
BUILD_PSXTMTESTS = True
# Build the Rhealstone benchmark programs (may be also enabled by
# BUILD_TESTS)
BUILD_RHEALSTONE = False
# Build the sample programs (may be also enabled by BUILD_TESTS)
BUILD_SAMPLES = True
# Build the SMP test programs (may be also enabled by BUILD_TESTS)
BUILD_SMPTESTS = False
# Build the single-processor test programs (may be also enabled by
# BUILD_TESTS)
BUILD_SPTESTS = False
# Build the timing test programs (may be also enabled by BUILD_TESTS)
BUILD_TMTESTS = False
# Build the unit test programs (may be also enabled by BUILD_TESTS)
BUILD_UNITTESTS = False
# Build the validation test programs (may be also enabled by
# BUILD_TESTS)
BUILD_VALIDATIONTESTS = False
# Sets the test verbosity of the RTEMS Test Framework.  Valid values
# are "Verbose", "Normal", and "Quiet".  For normal test runs you can
# use a verbosity of "Normal".  If you need a more detailed output,
# then you can set it to "Verbose".  For example, in case a regression
# occurred.  Reducing the verbosity level can significantly reduce the
# test duration especially on targets with a slow serial output
# device.  All verbosity levels produce enough output to notice failed
# test cases.  In particular, the begin and end of test information is
# not affected by the verbosity level.
RTEMS_TEST_VERBOSITY = Normal
# Default optimization flags for C and C++ compilers.
OPTIMIZATION_FLAGS = -O2 -g
# ABI flags
ABI_FLAGS = -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16
# enable I2C 1
STM32F4_ENABLE_I2C1 = False
# enable I2C 2
STM32F4_ENABLE_I2C2 = False
# enable UART 4
STM32F4_ENABLE_UART_4 = False
# enable UART 5
STM32F4_ENABLE_UART_5 = False
# enable USART 1
STM32F4_ENABLE_USART_1 = False
# enable USART 2
STM32F4_ENABLE_USART_2 = False
# enable USART 3
STM32F4_ENABLE_USART_3 = True
# enable USART 6
STM32F4_ENABLE_USART_6 = False
# Chip belongs to the STM32F10XXX family.
STM32F4_FAMILY_F10XXX = False
# Chip belongs to the STM32F4XXXX family.
STM32F4_FAMILY_F4XXXX = True
# HCLK frequency in Hz
STM32F4_HCLK = 16000000
# HSE oscillator frequency in Hz
STM32F4_HSE_OSCILLATOR = 8000000
# PCLK1 frequency in Hz
STM32F4_PCLK1 = 16000000
# PCLK2 frequency in Hz
STM32F4_PCLK2 = 16000000
# SYSCLK frequency in Hz
STM32F4_SYSCLK = 16000000
# baud for USARTs
STM32F4_USART_BAUD = 115200
# The default linker command file based on the BSP variant.
STM32F4_LINKCMDS = linkcmds.stm32f4
# Use the Termios interrupt mode in the console driver.
BSP_CONSOLE_USE_INTERRUPTS = True
# Do the clock tick processing on the boot processor on behalf of all
# other processors.
CLOCK_DRIVER_USE_ONLY_BOOT_PROCESSOR = False
# Section layout flags required for correct linker garbage collection.
# These flags are separated from OPTIMIZATION_FLAGS so that users may
# override optimization settings without removing the required section
# flags. Users may override these flags through the SECTION_FLAGS
# build option if different section handling behaviour is required.
SECTION_FLAGS = -ffunction-sections -fdata-sections
# Optimization flags passed to C and C++ compilers for the BSP.
BSP_OPTIMIZATION_FLAGS = ${SECTION_FLAGS} ${OPTIMIZATION_FLAGS}
# Optimization flags passed to C and C++ compilers for the CPU kit.
CPUKIT_OPTIMIZATION_FLAGS = ${SECTION_FLAGS} ${OPTIMIZATION_FLAGS}
# Optimization flags passed to C and C++ compiler for tests.
TEST_OPTIMIZATION_FLAGS = ${SECTION_FLAGS} ${OPTIMIZATION_FLAGS}
# If defined to a non-zero value, prints the some information in case
# of a fatal error.
BSP_VERBOSE_FATAL_EXTENSION = 1
# Flags passed to the linker.
LINKFLAGS = 
# Flags passed to the linker at the end of the link command.
LDFLAGS = -Wl,--gc-sections
# Install the legacy application Makefile framework.
INSTALL_LEGACY_MAKEFILES = True
# If defined to a non-zero value, prints the exception context when an
# unexpected exception occurs.
BSP_PRINT_EXCEPTION_CONTEXT = 1
# If defined to a non-zero value, reset the board when the application
# exits.
BSP_RESET_BOARD_AT_EXIT = 1
# If defined to a non-zero value, print a message and wait until
# pressed before resetting board when application exits.
BSP_PRESS_KEY_FOR_RESET = 0
