services:
  dev:
    build:
      context: .
    working_dir: /opt/rtems-llvm
    volumes:
      - .:/opt/rtems-llvm
      - llvm-build:/opt/rtems-llvm/src/rtems-rsb/rtems/build
      - /dev/bus/usb:/dev/bus/usb
    command: sleep infinity
    stdin_open: true
    tty: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0:rw"
    group_add:
      - keep-groups
    security_opt:
      - label=disable
    annotations:
      run.oci.keep_original_groups: "1"

volumes:
  llvm-build: