#!/bin/bash
WRAPPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REAL_CLANGXX="${WRAPPER_DIR}/../bin/clang++"
REAL_GXX="${WRAPPER_DIR}/../bin/aarch64-rtems7-g++"

args=()
link=1
for a in "$@"; do
  case "$a" in
    -c|-S|-E) link=0 ;;
  esac
  args+=("$a")
done

if [[ $link -eq 0 ]]; then
  exec "$REAL_CLANGXX" "${args[@]}"
else
  filtered=()
  for a in "${args[@]}"; do
    [[ $a == --target=* ]] && continue
    filtered+=("$a")
  done
  exec "$REAL_GXX" -qrtems "${filtered[@]}"
fi
