#!/bin/bash
REAL_CLANGXX="../bin/clang++"
REAL_GXX="../bin/aarch64-rtems7-g++" # TODO: should get the --target and pick the correct gcc from there

args=()
link=1
for a in "$@"; do
  case "$a" in
    -c|-S|-E) link=0 ;;
  esac
  args+=("$a")
done

if [[ $link -eq 0 ]]; then
  exec "$REAL_CLANGXX" "${args[@]}"
else
  filtered=()
  for a in "${args[@]}"; do
    [[ $a == --target=* ]] && continue
    filtered+=("$a")
  done
  exec "$REAL_GXX" -qrtems "${filtered[@]}"
fi
