#!/bin/bash
WRAPPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REAL_CLANG="${WRAPPER_DIR}/../bin/clang"
REAL_GCC="${WRAPPER_DIR}/../bin/aarch64-rtems7-gcc"

args=()
link=1
for a in "$@"; do
  case "$a" in
    -c|-S|-E) link=0 ;;
  esac
  args+=("$a")
done

if [[ $link -eq 0 ]]; then
  exec "$REAL_CLANG" "${args[@]}"
else
  filtered=()
  for a in "${args[@]}"; do
    [[ $a == --target=* ]] && continue
    filtered+=("$a")
  done
  exec "$REAL_GCC" -qrtems "${filtered[@]}"
fi
